#!/usr/bin/env bash
INSTALL_DIR=/root
FAIL2BAN=1
while getopts ":f" OPTION
do
  case $OPTION in
  f)
    FAIL2BAN=0
    ;;
  \?)
    echo "Used for the help menu $OPTARG"
    exit 999
    ;;
  esac
done


SCRIPT_NAME=keys4user
INSTALL_PATH=$INSTALL_DIR/$SCRIPT_NAME
SSHD_CONF=/etc/ssh/sshd_config
FAIL2BAN_SSH_PATH=/etc/fail2ban/fail2ban.d/ssh.local

read -d '' KEYS4USER <<'SCRIPT-DOC'
#!/usr/bin/env bash
HOME_DIR=$(eval echo "~$1")
SSH_DIR=$HOME_DIR/.ssh
KEY_LOC=$SSH_DIR/key_locations
CACHE=$KEY_LOC.cache
AUTH_KEYS=""

if [ -e "$KEY_LOC" ]
then
  while read URL
    do
    if [ ! -z "$URL" ]
    then
      KEY=$(curl -sfL "$URL")
      CURL_EXIT_STATUS=$?
      if [ $CURL_EXIT_STATUS != 0 ]
      then
        cat $CACHE
        exit $?
      fi
      AUTH_KEYS+="$KEY$(echo)"
    fi
  done <$KEY_LOC
fi

if [ ! -z "$AUTH_KEYS" ]
then
  touch $CACHE
  chown $1:$1 $CACHE
  chmod 0644 $CACHE
  printf "$AUTH_KEYS" | tee "$CACHE"
fi
SCRIPT-DOC

read -d '' SSH_JAIL_CONF <<'EOF'
[ssh]

enabled = true
port	= ssh
filter	= sshd
action   = iptables[name=SSH, port=ssh, protocol=tcp]
logpath  = /var/log/auth.log
maxretry = 3
bantime = 900
EOF

install_script () {
  printf "Installing $SCRIPT_NAME to $INSTALL_PATH..."

  touch $INSTALL_PATH || exit 1
  chown root $INSTALL_PATH || exit 2
  chmod 0755 $INSTALL_PATH || exit 3
  printf "$KEYS4USER" > $INSTALL_PATH || exit 4
}

install_SSH_config () {
  printf "Installing required config to $SSHD_CONF..."

  (grep "AuthorizedKeysCommand" $SSHD_CONF | grep -vq ^[\#] || printf "\n\nAuthorizedKeysCommand $INSTALL_PATH\n" >> $SSHD_CONF) || exit 5
  (grep "AuthorizedKeysCommandUser" $SSHD_CONF | grep -vq ^[\#] || printf "AuthorizedKeysCommandUser root\n" >> $SSHD_CONF) || exit 6
}

install_fail2ban () {
  printf "Installing fail2ban..."

  apt-get update -y || exit $?
  apt-get install fail2ban -y || exit $?

  touch $FAIL2BAN_SSH_PATH || exit 7
  chown root $FAIL2BAN_SSH_PATH || exit 8
  chmod 0755 $FAIL2BAN_SSH_PATH || exit 9
  printf "$SSH_JAIL_CONF" > $FAIL2BAN_SSH_PATH || exit 10
}

install () {
  install_script
  install_SSH_config
  if (("$FAIL2BAN" > "0"))
  then
    install_fail2ban
  fi
}


install
