#!/usr/bin/env bash
INSTALL_DIR=/usr/local/bin
SCRIPT_NAME=keys4user
INSTALL_PATH=$INSTALL_DIR/$SCRIPT_NAME
SSHD_CONF=/etc/ssh/sshd_config

read -d '' KEYS4USER <<'SCRIPT-DOC'
#!/usr/bin/env bash
HOME_DIR=$(eval echo "~$1")
SSH_DIR=$HOME_DIR/.ssh
KEY_LOC=$SSH_DIR/key_locations
CACHE=$KEY_LOC.cache
AUTH_KEYS=""

if [ -e "$KEY_LOC" ]
then
  while read URL
    do
    if [ ! -z "$URL" ]
    then
      KEY=$(curl -sfL "$URL")
      CURL_EXIT_STATUS=$?
      if [ $CURL_EXIT_STATUS != 0 ]
      then
        cat $CACHE
        exit $?
      fi
      AUTH_KEYS+="$KEY$(echo)"
    fi
  done <$KEY_LOC
fi

if [ ! -z "$AUTH_KEYS" ]
then
  touch $CACHE
  chown $1:$1 $CACHE
  chmod 0644 $CACHE
  printf "$AUTH_KEYS" | tee "$CACHE"
fi
SCRIPT-DOC

install () {

  touch $INSTALL_PATH
  chown root $INSTALL_PATH
  chmod 0755 $INSTALL_PATH
  printf "$KEYS4USER" > $INSTALL_PATH

  grep "AuthorizedKeysCommand" $SSHD_CONF | grep -vq ^[\#] || echo "AuthorizedKeysCommand $INSTALL_PATH" >> $SSHD_CONF
  grep "AuthorizedKeysCommandUser" $SSHD_CONF | grep -vq ^[\#] || echo "AuthorizedKeysCommandUser root" >> $SSHD_CONF

}

install
